services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app

    # carga tu .env
    env_file:
      - .env

    depends_on:
      - db

    # fuerza a conectar al servicio 'db' de tu Compose
    environment:
      DB_HOST: db

    command: flask run --host=0.0.0.0

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
